# Generated by Django 5.2.4 on 2025-07-05 13:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=10, max_digits=20)),
                ('perimeter', models.DecimalField(decimal_places=10, max_digits=20)),
                ('county3', models.DecimalField(db_column='county3_', decimal_places=10, max_digits=20)),
                ('county3_id', models.DecimalField(decimal_places=10, max_digits=20)),
                ('county', models.CharField(max_length=100)),
                ('shape_leng', models.DecimalField(decimal_places=10, max_digits=20)),
                ('shape_area', models.DecimalField(decimal_places=10, max_digits=20)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'roads',
                'managed': False,
            },
        ),
    ]
