# Generated by Django 5.2.4 on 2025-07-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roads',
            table='nairobi',
        ),
    ]
